const FLAGS: Record<string, string> = {
  'australia': '🇦🇺',
  'malaysia': '🇲🇾',
  'bahrain': '🇧🇭',
  'san marino': '🇸🇲',
  'great britain': '🇬🇧',
  'uk': '🇬🇧',
  'britain': '🇬🇧',
  'spain': '🇪🇸',
  'monaco': '🇲🇨',
  'canada': '🇨🇦',
  'europe': '🇪🇺',
  'france': '🇫🇷',
  'austria': '🇦🇹',
  'germany': '🇩🇪',
  'hungary': '🇭🇺',
  'belgium': '🇧🇪',
  'italy': '🇮🇹',
  'emilia romagna': '🇮🇹',
  'tuscany': '🇮🇹',
  'usa': '🇺🇸',
  'united states': '🇺🇸',
  'las vegas': '🇺🇸',
  'miami': '🇺🇸',
  'japan': '🇯🇵',
  'brazil': '🇧🇷',
  'argentina': '🇦🇷',
  'mexico': '🇲🇽',
  'singapore': '🇸🇬',
  'turkey': '🇹🇷',
  'abu dhabi': '🇦🇪',
  'uae': '🇦🇪',
  'korea': '🇰🇷',
  'india': '🇮🇳',
  'russia': '🇷🇺',
  'azerbaijan': '🇦🇿',
  'china': '🇨🇳',
  'netherlands': '🇳🇱',
  'qatar': '🇶🇦',
  'saudi arabia': '🇸🇦',
  'portugal': '🇵🇹',
  'vietnam': '🇻🇳',
  'luxembourg': '🇱🇺',
  'south africa': '🇿🇦',
  'morocco': '🇲🇦',
  'pacific': '🇯🇵',
  'switzerland': '🇨🇭',
  'south korea': '🇰🇷',
}

export function countryFlag(country: string | null | undefined): string | null {
  if (!country) return null
  const key = country.trim().toLowerCase()
  return FLAGS[key] ?? null
}